image: docker-reg.devops.xiaohongshu.com/fe/fe-ci:v1.8.1

before_script:
  - node -v
  - formula -V
  - export PKGLEFT=${CI_COMMIT_TAG%@*}
  - export PKGNAME=${PKGLEFT/@xhs\//}
  - export PKGNAME2=${PKGNAME/beer-docs-site/docs-site}
  - echo $PKGNAME

stages:
  - deploy

# pages:
#   stage: deploy
#   script:
#     - lerna bootstrap
#     - cd packages/docs-site
#     - npm run deploy:docs-pages
#   only:
#     - master
#   artifacts:
#     paths:
#     - public

deploy:feature:
  stage: deploy
  when: manual
  script:
    - lerna changed
    - git checkout $CI_COMMIT_REF_NAME
    - npm run version:base -- prerelease
          --preid=$CI_JOB_ID
          --no-git-tag-version --yes
          --allow-branch feature*
    - cd packages/git-flow-chart
    - npm publish --tag=beta
  only:
    - branches
  except:
    - develop
    - master
  allow_failure: false

# deploy:npm:
#   stage: deploy
#   script:
#     - ls
#     - cd packages/$PKGNAME2
#     - npm publish
#   only:
#     - tags
#   except:
#     - branches
#     - master
#     - develop
#     - /^v.*$/
